import type { Metadata } from "next";
// import { FontAwesomeIcon } from "@fortawesome/fontawesome-svg-core";
// import { FontawesomeObject } from "@fortawesome/fontawesome-svg-core";
// import { FaBars, FaBell, FaList, FaUser } from "react-icons/fa";

// import Header from "@/components/LayoutComponent/layout";
import LayoutComponent from "@/components/LayoutComponent/layout";
export const metadata: Metadata = {
  title: "Dashboard",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
      <>
        <LayoutComponent>
            {children}
        </LayoutComponent>
      </>
  );
}
